name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a9162cfbb97cd6f8a7225c605bafa963bf99249d5b647264783157b4ac5e19"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
