name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6-server-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ac94b1b85970357e2645b3d31e7f47deaab53fd4a23797f1b687e4dd5299c46"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
