name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edc1117ec9f29bbf7fee62bb790e059e36b7ca6639576a04bac795e1dd032d16"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
