name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6-server-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f5ca444d228b34cb7c8789ad923e027d232b4875f8c5f1b2cb15c8a552f74c"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
