name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6-server-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "464cb2a665ae684a16ff89f99cc2ef8ba7ad06798d0d784528eccb9312f47d1a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
