name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42886f10363ff46d18fd485e126defe4471dc63e462c37de1fafff6524818fdb"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
