name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e99697b72e14ebff2736f6c8ce4c62a8091ada4aa234b6f57aaba6bf509fea25"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
