name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de9e6d05956d7500bf59e078ecb4dea7eb04a24f0d7d3e15b9a9e109d8baff02"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
