name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3a7ef1686865920d529f2511dbc00be83f1462ad627199024c3fd24c49395e9"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
