name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a7e3e74f065016e1f551ff3e890be1761b844ab6f1e5f89cf9c363132c908e9"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
