name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac793161dbc5adfcf9a2df2102c387950a88ea06a9647ee4af676e73eea2f8b5"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
