name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6-server-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b09e59072a029452490ab145c04ca91788a1b850dc9f6fbd9da036d6ee7aad21"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
