name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.0.6-server-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c61c05b938551405166fb42e7fcb3737e5171db5f2478535a6acc3f3a369c5d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
